# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: email.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import email_pb2


class EmailsBase(abc.ABC):

    @abc.abstractmethod
    async def SendMail(self, stream: 'grpclib.server.Stream[email_pb2.SendReq, email_pb2.SendRes]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/emails.Emails/SendMail': grpclib.const.Handler(
                self.SendMail,
                grpclib.const.Cardinality.UNARY_UNARY,
                email_pb2.SendReq,
                email_pb2.SendRes,
            ),
        }


class EmailsStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SendMail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/emails.Emails/SendMail',
            email_pb2.SendReq,
            email_pb2.SendRes,
        )
