# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article/article.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61rticle/article.proto\x12\x07\x61rticle\x1a\x1bgoogle/protobuf/empty.proto\"J\n\x07\x41rticle\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"\'\n\x15\x41rticleCreateResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"I\n\x13\x41rticleListResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\"\n\x08\x61rticles\x18\x02 \x03(\x0b\x32\x10.article.Article2\x8a\x01\n\x0e\x41rticleService\x12:\n\x06\x43reate\x12\x10.article.Article\x1a\x1e.article.ArticleCreateResponse\x12<\n\x04List\x12\x16.google.protobuf.Empty\x1a\x1c.article.ArticleListResponseB>Z<github.com/trk54ylmz/blog-microservice-example/proto/articleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'article.article_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/trk54ylmz/blog-microservice-example/proto/article'
  _ARTICLE._serialized_start=63
  _ARTICLE._serialized_end=137
  _ARTICLECREATERESPONSE._serialized_start=139
  _ARTICLECREATERESPONSE._serialized_end=178
  _ARTICLELISTRESPONSE._serialized_start=180
  _ARTICLELISTRESPONSE._serialized_end=253
  _ARTICLESERVICE._serialized_start=256
  _ARTICLESERVICE._serialized_end=394
# @@protoc_insertion_point(module_scope)
