# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproject.proto\x12\x0c\x64\x65mo_project\"5\n\x14\x43reateProjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"E\n\x10\x43reateTagRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\"8\n\x11GetProjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"T\n\x0fProjectResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\x04tags\x18\x03 \x03(\x0b\x32\x19.demo_project.TagResponse\";\n\x0bTagResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t2\xf6\x01\n\nProjectSvc\x12R\n\rcreateProject\x12\".demo_project.CreateProjectRequest\x1a\x1d.demo_project.ProjectResponse\x12\x46\n\tcreateTag\x12\x1e.demo_project.CreateTagRequest\x1a\x19.demo_project.TagResponse\x12L\n\ngetProject\x12\x1f.demo_project.GetProjectRequest\x1a\x1d.demo_project.ProjectResponseB6Z4github.com/Joker666/microservice-demo/protos/projectb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/Joker666/microservice-demo/protos/project'
  _CREATEPROJECTREQUEST._serialized_start=31
  _CREATEPROJECTREQUEST._serialized_end=84
  _CREATETAGREQUEST._serialized_start=86
  _CREATETAGREQUEST._serialized_end=155
  _GETPROJECTREQUEST._serialized_start=157
  _GETPROJECTREQUEST._serialized_end=213
  _PROJECTRESPONSE._serialized_start=215
  _PROJECTRESPONSE._serialized_end=299
  _TAGRESPONSE._serialized_start=301
  _TAGRESPONSE._serialized_end=360
  _PROJECTSVC._serialized_start=363
  _PROJECTSVC._serialized_end=609
# @@protoc_insertion_point(module_scope)
